# NOTE: This file can be added either in UI or in API which will manage all your routes
# REFERENCE: 
# https://kubernetes.io/docs/concepts/services-networking/ingress/
# https://medium.com/@Oskarr3/setting-up-ingress-on-minikube-6ae825e98f82
# To run/expose locally use -> kubectl expose deployment cornplex-api-deployment --type=LoadBalancer --name=loadbalancer-service

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cornplex-api-ingress-service
  # namespace: cornplex-api-ingress-service
  # labels:
  #   app: cornplex-api-ingress-service
spec:
  defaultBackend:
    service:
      name: default-http-backend
      port:
        number: 80
  rules:
    - host: ""
      http:
        paths:
          # - path: / # Path For UI
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: cornplex-ui-service # this should match your api-service-deployment metadata:name
          #       port:
          #         number: 4200
          - path: /swagger/ # Path For SWAGGER
            pathType: Prefix
            backend:
              service:
                name: cornplex-api-service # this should match your api-service-deployment metadata:name
                port:
                  number: 5000
          - path: /api/ # Path For API
            pathType: Prefix
            backend:
              service:
                name: cornplex-api-service # this should match your api-service-deployment metadata:name
                port:
                  number: 5000
#   externalIPs:
#     - 80.11.12.10

# ---

# Sample 1

# kind: Service
# apiVersion: v1
# metadata:
#   name: ingress-nginx
#   namespace: ingress-nginx
#   labels:
#     app: ingress-nginx
# spec:
#   selector:
#     app: ingress-nginx
#   ports:
#     - name: http
#       port: 80
#       targetPort: http
#     - name: https
#       port: 443
#       targetPort: http
#   externalIPs:
#     - 80.11.12.10
